[project]
name = "aps-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "autodesk-forge-sdk>=0.1.2",
    "ipykernel>=6.29.5",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
